### PR TITLE
Create local-devex-com-forward.md

### PR DESCRIPTION
**Pull request by dsager**

### CODE REVIEW

**Comment by EdLittle** [comment]
+1

**Comment by towanda** [comment]
+1

**Comment by christofdamian** [comment]
+1 A while ago I suggested to have local.devex.com as 127.0.0.1 in our public DNS. That would avoid the /etc/hosts change for everyone. Not sure why we didn't do that @Devex/infrastructure

**Comment by jhmarina** [comment]
+1

**Comment by dsager** [comment]
The etc/hosts way would still be a little faster and also work offline, but it could also be additionally :)

**Comment by nicolas-fricke** [comment]
+1

**Comment by nicolas-fricke** [comment]
Added a section on how to do the same for Mac OS (a bit more complicated there ...): [PR #3](https://github.com/Devex/snippets/pull/3)

**Pull request merged**
