### PR TITLE
Create manu_aliases.sh

### PR DESCRIPTION
**Pull request by towanda**

### CODE REVIEW

**Comment by nicolas-fricke** [comment]
Could you maybe rename the file to just `aliases.sh`? :)

**Comment by towanda** [comment]
@nicolas-fricke the intention was to have some way to differentiate who are the aliases from, because everyone may have a different one. I would go for a better naming, but if it helps to differentiate this.

**Comment by nicolas-fricke** [comment]
Hm, I'm not yet entirely sure what the purpose of this repo is, none of the scripts will probably work _for everyone_, but it can be a good place to see if there's something someone might re-use.. So I think I'd not use _exactly this_ alias file, but I might c&p some aliases out and then use those, hence just `aliases.sh` would be fine for me. Other thoughts?

**Comment by towanda** [comment]
@nicolas-fricke I think more or less many of us use command line aliases, so I thought It was easier to have a name in the file to differentiate different aliases, imagine if three developers have the same alias for different commands, something which happens often..

So for me it doesn't make sense to have an unique name, since it's more about see how other people name different commands. But yes, It depends on the purpose of this repo, which I thought would be to share snippets or utilities which could be useful or interesting.

**Comment by nicolas-fricke** [comment]
Alright, also fine with me :)

**Comment by nicolas-fricke** [comment]
Oh, now you've already closed the PR..? :cry:

**Pull request closed without merging**
